### PR TITLE
LTO riscv64

### LINKED ISSUE #2064: llvm_mode LTO instrumentlist and persistent tests fails on Alpine Linux riscv64
**IMPORTANT**

AFLplusplus-4.20c

**Describe the bug**
On alpine linux, riscv64 the LTO llvm_mode test fails.

```
[*] Testing: LTO llvm_mode
[!] LTO llvm_mode failed   
[!] llvm_mode LTO instrumentlist feature compilation failed
[!] llvm_mode LTO persistent mode feature compilation failed
```

**To Reproduce**

On an Alpin eLinux riscv64 machine run:
```
        export PATH="$PATH:/usr/lib/llvm17/bin"
        export NO_NYX=1
        export AFL_NO_X86=1
        export LLVM_LTO=1
        make PREFIX=/usr all

        CFLAGS= CXXFLAGS= make AFL_NO_X86=1 test
```

**Expected behavior**
Test passes

**Screen output/Screenshots**

```
[*] Testing: LTO llvm_mode
[!] LTO llvm_mode failed
[!] llvm_mode LTO instrumentlist feature compilation failed
[!] llvm_mode LTO persistent mode feature compilation failed
```

**Additional context**

This was discovered on riscv64.

### PR DESCRIPTION
**Pull request by nbars**
Bug seem to be fixed upstream. Add support to run tests on different architectures using QEMU and fix errors in the RISCV build. Not sure if we want to add them to the CI for ARM & RISCV?

Fixes #2064

### CODE REVIEW

File: test/test-llvm.sh [hunk 1]
```diff
@@ -221,7 +221,7 @@ test -e ../afl-clang-fast -a -e ../split-switches-pass.so && {
 
   AFL_LLVM_INSTRUMENT=AFL AFL_DEBUG=1 AFL_LLVM_LAF_SPLIT_SWITCHES=1 AFL_LLVM_LAF_TRANSFORM_COMPARES=1 AFL_LLVM_LAF_SPLIT_COMPARES=1 ../afl-clang-fast -o test-compcov.compcov test-compcov.c > test.out 2>&1
   test -e test-compcov.compcov && test_compcov_binary_functionality ./test-compcov.compcov && {
-    grep --binary-files=text -Eq " [ 123][0-9][0-9] location| [3-9][0-9] location" test.out && {
+    grep$GREPAOPTION -Eq " [ 123][0-9][0-9] location| [3-9][0-9] location" test.out && {
```
Comment (vanhauser-thc) [inline test/test-llvm.sh]: is this missing a space?

**Comment by vanhauser-thc** [comment]
If this is an LLVM bug, why would we need a test in AFL++?

**Comment by nbars** [comment]
To catch future errors for those platforms

**Comment by vanhauser-thc** [comment]
thanks
